### ISSUE TITLE
Unable to install cqkit using pip

### ISSUE THREAD

**Issue by fungiboletus** [michaelgale/cq-kit#5]
Hei, I'm unable to install cqkit using pip. I tried with various versions of Python, on Linux and MacOS.

Example:
```
docker run -it --rm  python:3.10-slim-bullseye bash
root@c71a37b4384e:/# pip install cqkit
Collecting cqkit
  Downloading cqkit-0.5.0.tar.gz (47 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.1/47.1 kB 1.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-d86usskz/cqkit_8552ef1848204e9dbc49f82914745b8b/setup.py", line 14, in <module>
          with open(loc + "/requirements.txt") as f:
      FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-d86usskz/cqkit_8552ef1848204e9dbc49f82914745b8b/requirements.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

[notice] A new release of pip is available: 23.0.1 -> 23.1
[notice] To update, run: pip install --upgrade pip
```

**Comment by michaelgale** [comment]
Glad to hear it works.   Thanks for letting me know about the issue.
